---
inherit_gem:
  voxpupuli-test: rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Include:
    - "**/*.rb"
    - Gemfile
    - Rakefile
    - "*.gemspec"
  Exclude:
    - ".vendor/**/*"
    - pkg/**/*
    - spec/fixtures/**/*
    - vendor/**/*
    - dist/**/*

Layout/LineLength:
  Description: People have wide screens, use them.
  Max: 200

RSpec/HookArgument:
  Description: Prefer explicit :each argument, matching existing module's style
  EnforcedStyle: each

Style/BlockDelimiters:
  Description:
    Prefer braces for chaining. Mostly an aesthetical choice. Better to
    be consistent then.
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Description: Compact style reduces the required amount of indentation.
  EnforcedStyle: compact

Layout/DotPosition:
  EnforcedStyle: leading

Style/TrailingCommaInArguments:
  Description:
    Prefer always trailing comma on multiline argument lists. This makes
    diffs, and re-ordering nicer.
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Description:
    Prefer always trailing comma on multiline literals. This makes diffs,
    and re-ordering nicer.
  EnforcedStyleForMultiline: comma

Style/SymbolArray:
  Description: Using percent style obscures symbolic intent of array's contents.
  EnforcedStyle: brackets

Style/Documentation:
  Exclude:
    - lib/puppet/parser/functions/**/*
    - spec/**/*

Style/WordArray:
  EnforcedStyle: brackets

Layout/HashAlignment:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/SafeNavigationConsistency:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

Security/Open:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
